# Generated by Django 5.1.3 on 2024-11-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255, verbose_name='Название книги')),
                ('book_description', models.CharField(max_length=600, verbose_name='Краткое описание')),
                ('book_price', models.PositiveIntegerField(verbose_name='сколько стоит книга?')),
                ('book_release', models.DateField(verbose_name='Дата выхода')),
                ('book_genre', models.CharField(max_length=255, verbose_name='Жанр книги')),
                ('authors_email', models.EmailField(max_length=254, verbose_name='почта автора')),
                ('authors_name', models.CharField(max_length=255, verbose_name='Имя автора')),
            ],
        ),
    ]
