# Generated by Django 5.1.3 on 2024-11-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='books',
            name='book_genre',
            field=models.CharField(choices=[('Fantastic', 'Фантастика'), ('Adventure', 'Приключения'), ('Science', 'Научная')], max_length=255, verbose_name='Жанр книги'),
        ),
    ]
