# Generated by Django 5.1.3 on 2024-11-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_alter_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
